// import Head from 'next/head'
import DefaultLayout from '../../components/layout/main'

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <DefaultLayout>Content here</DefaultLayout>

      <footer></footer>
    </div>
  )
}
